### ISSUE TITLE
Call in LIFO order instead of FIFO

### ISSUE THREAD

**Issue by ronag** [jshttp/on-finished#17]
It would be useful if the callbacks were called in LIFO order instead of FIFO.

e.g.
```javascript
const fd = await fs.open(filePath)
onFinished(res, () => fs.close(fd))
await fs.write('test')
onFinished(res, () => fs.fsync(fd)
```

**Comment by dougwilson** [comment]
The ordering is unfortunately not a negotiable part, for the one part it being a nightmare if multiple versions are used at once with different semantics, and that the ordering matches that of event listeners, which we did not define and does not provide any real interface to run in reverse order.

**Comment by ggoodman** [comment]
I've submitted a PR for optional LIFO ordering in #28.
