### ISSUE TITLE
Response Body missing  After on-finished called

### ISSUE THREAD

**Issue by zeeshanalisyed** [jshttp/on-finished#24]
I just Have one problem, I don't understand after I call `on-finished`  function i don't get response body, now my requirement was not to use response.end or response.write function, or to manage events just call on-finished, after i would be able to receive data in response.body.

`Is it possible that on-finished manages the body placement?`
`Is it a good way to hook response body when we are using on-finished function?`

may be something is missing for me here, if yes then i apologize.

**Comment by dougwilson** [comment]
Hi @zeeshanalisyed I'm not sure I fully understand your question; this module is just a wrapper around adding a few event listeners; it doesn't manage the body placement, read the body, or anything similar. At the high level, you can think of `onFinished(response, func)` being the same as `response.on('finish', func)`.

**Comment by zeeshanalisyed** [comment]
My Question was if I place a listener like below
```
onFinished(res, cutsomeEndListener)

function cutsomeEndListener(err, res){
  //res.body ?
}
```
Would I be able to access res.body? One thing I know that via `res.end((bodyChunk) => bodyChunk)`  i can get it, but can i get the response body in `cutsomeEndListener`?

**Comment by dougwilson** [comment]
If you set `res.body` somewhere, then yes.

**Comment by zeeshanalisyed** [comment]
Ok thank you for the response now it's clear.

**Comment by JeremyCraigMartinez** [comment]
So I will have to copy and paste `res.body = responseObject; res.send(responseObject);` everywhere in my codebase? Or is there a way to access it after only called `res.send`?

**Comment by balasuar** [comment]
> So I will have to copy and paste `res.body = responseObject; res.send(responseObject);` everywhere in my codebase? Or is there a way to access it after only called `res.send`?

For non-production purposes, I needed to record request and response, and ran into this issue. To solve it, I patched `res.send` in an expressjs middleware and stored of the arguments, which are then accessed inside `onFinished`

```
app.use((req, res, next) => {

  const oldSend = res.send;

  res.send = (...sendArgs) => {
    res.sendArgs = sendArgs;
    oldSend.apply(res, sendArgs);
  }

  onFinished(res, async (err, response) => {
    console.log(req.originalUrl, res.sendArgs);
  });
  
  return next();
}
```

I wouldn't recommend this approach for production workloads, but for development purposes it should work fine.
