### ISSUE TITLE
on-finished vs Node stream.finished()

### ISSUE THREAD

**Issue by felipeptcho** [jshttp/on-finished#33]
This lib is very similar to the NodeJS `stream.finished()` function to me. If I'm using NodeJS version 10 or greater, is there any real advantage of using this lib? Thanks for your time.

https://nodejs.org/api/stream.html#stream_stream_finished_stream_options_callback

**Comment by dougwilson** [comment]
Provably not. This module is, in essence, a helper for what Node.js did not provide (easily) out of the box. It is also HTTP specific, so if you're not interacting with HTTP streams this module wouldn't really be relevant anyhow (vs the .finished() built in API which is for streams in general).

**Comment by felipeptcho** [comment]
Got it! Thanks for the quick reply.
