### ISSUE TITLE
Callback fires immediatly on sendFile

### ISSUE THREAD

**Issue by schelkun** [jshttp/on-finished#34]
When I use express to send some file via:

```js
onFinished(res, (err, res) => {
  console.log('transfer done'); // will fire before file sent to user
});

res.sendFile(filepath);
```

Callback will be fired before file was sent. How can I handle sendFile with `on-finished`?

**Comment by dougwilson** [comment]
Just use the callback that res.sendFile.

As for what you are directly reporting I am not able to reproduce. I would need a fully reproducible example including the specific sequence of steps to recreate what you are seeing in order to investigate.

**Comment by schelkun** [comment]
Thank you for your fast reply!
Just used callback, it fires immediatly too :(

**Comment by dougwilson** [comment]
Does the callback give you any error?

**Comment by schelkun** [comment]
No it does not :(

**Comment by dougwilson** [comment]
Dang. I would need a fully reproducible example including the specific sequence of steps to recreate what you are seeing in order to investigate.

**Comment by ryhinchey** [comment]
I can replicate the issue only when making requests via a web browser.  Here's a repo that can reproduce the issue: https://github.com/ryhinchey/on-finished-issue-reproduction

```js
var path = require('path');
var express = require('express');
var onFinished = require('on-finished');

var app = express();

app.use('/', (req, res) => {

  onFinished(res, (err, res) => {
    console.log('transfer done 1');
  });

  res.sendFile(path.join(process.cwd(), 'test.txt'), function (err) {
    if (err) {
      console.log(err);
    } else {
      console.log('sent file');
    }
  });
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`App is listening on port ${PORT}`));
```

hit `localhost:5000` in a web browser and you'll see:
```
transfer done
sent file
```

`curl localhost:5000` and you'll see:
```
sent file
transfer done
```

**Comment by dougwilson** [comment]
Thanks for that @ryhinchey ! Unfortunately it still does not replicate for me. Here is the output when I load `http://localhost:5000` in Chrome:
```
$ node index.js 
App is listening on port 5000
sent file
transfer done
sent file
transfer done
```

**Comment by dougwilson** [comment]
The reason why it shows two requests when I load it in my Chrome is that Chrome made two requests: one for `http://localhost:5000/` and one for `http://localhost:5000/favicon.ico`.

**Comment by ryhinchey** [comment]
Yah I get two requests too which is expected.  What version of node are you running?

**Comment by dougwilson** [comment]
13.8.0

**Comment by ryhinchey** [comment]
I switched to 13.8.0 and am still getting this in Chrome & Firefox
```
transfer done
sent file
transfer done
sent file
```

I'm on macos `10.15.2`

**Comment by dougwilson** [comment]
I have tried both Chrome & Firefox as well, but on Windows. I wonder if it's Mac OS-specific? Without access to a Mac OS X machine, though, I cannot test if that is the case (or debug and determine a fix). Would you be able to debug through and determine why the "transfer done" is being printed before the "sent file" on your machine?

**Comment by ryhinchey** [comment]
Yah I’ll look into it this week

**Comment by dougwilson** [comment]
Awesome, thank you! Also, just wanted to clarify that the callback in `res.sendFile` is _after_ the file has finished being sent (vs when it just starts to send it). I think you know that, but reading back through everything, I just wanted to make sure that was unambiguous :) _Technically_ the resulting order of the `console.log`s above doesn't matter as long as they both occurs _after_ the data has finished being sent. If you added like `Date.now()` to your logs are they occurring at the same time?

**Comment by ryhinchey** [comment]
The logs are occurring at the same time.  Below is a  sampling of `curl` and browser(Chrome) requests. 

```
curl
1582081421112 sent file
1582081421113 transfer done

1582081421822 sent file
1582081421823 transfer done

browser
1582081460104 transfer done
1582081460104 sent file
1582081460152 transfer done
1582081460152 sent file

1582081463115 transfer done
1582081463115 sent file
1582081463149 sent file
1582081463149 transfer done
```

 I'm not sure  why the `console.log` order is different between curl and browser requests on macos or if it even should be considered a bug.   FWIW if you put  `onFinished` inside the `sendFile` callback, I get the log order I'd expect.

```js
  res.sendFile(path.join(process.cwd(), 'test.txt'), function (err) {
    onFinished(req, (err) => {
      console.log(Date.now(), 'transfer done');
    })
    
    if (err) {
      console.log(err);
    } else {
      console.log(Date.now(), 'sent file');
    }
  });
```

**Comment by dougwilson** [comment]
This module doesn't do anything specific to guarantee any kind of ordering; it's triggered off the incoming events from Node.js core HTTP response objects. If the only thing here is just the order is not deterministic, then it doesn't sound like there is anything wrong here, as this module's contract never promises any specific ordering, only that the callback is fired at some point after the request or response is completed (depending on which one you passed in).

Thank you for all your investigation!

**Comment by jonchurch** [comment]
I agree this isn't a bug because there's not contract violation here. I'm leaving my notes for anyone who is interested in this, as it had piqued my interest.

One thing to keep in mind is that `res.sendFile` is also using `onFinished` under the hood. I think maybe the `res.sendFile` callback gets queued up after the initial call to `onFinished` in the code. That doesn't make much sense for the behavior observed, so I could be off base on that entirely.

`sendFile` triggers it's callback in a `setImediate` handler, which could be part of the non-deterministic nature of this issue. 

Ultimately the difference between curl and the browser most likely relates to the particulars of how each making their HTTP request. 

* `onFinished` is orchestrating the behavior for both of these functions running their callbacks
* `onFinished` listens to low level events of the HTTP API
* The HTTP API relies on streams, whos events are not guaranteed to happen in the same order everytime

Again, I don't think this is a bug, but these are my notes for anyone who might stumble upon this later.
