### ISSUE TITLE
Pipelining and Socket handlers

### ISSUE THREAD

**Issue by calebboyd** [jshttp/on-finished#38]
I noticed that the same issue fixed [here](https://github.com/jshttp/on-finished/commit/e7a6848374adb5f0b6668b064e75ce0fb34ff6c3) occurs when a client is pipelining requests to a node server using on-finished for response messages. The pipelined requests cause the response to have the same socket instance, which on-finished is repeatedly attaching new handlers to.

Would a PR adding tests for this case and implementing the same approach (queueing listeners) be considered?

**Comment by dougwilson** [comment]
Yes, definitely. Even just a test case is great to get if you're not sure on the implementation.

**Comment by calebboyd** [comment]
Cool, I added a test case -- I was looking at the CI matrix and it looks like if I add an implementation it will have to work in Node 0.8?

**Comment by dougwilson** [comment]
Thank you! Yes, that is correct, but I am happy to help make that work if you cannot get it there.

Also to note, it seems that the test case you added in that PR is passing, so it would seem that either it doesn't replicate the issue, there is something wrong in the test case, or some other variable in play not replicated in the test case.

**Comment by calebboyd** [comment]
Thats weird - they were failing on my mac with a lower number of pipelined requests. Upping the number has them now failing in CI
