### ISSUE TITLE
Grammatical error in Readme.md file

### ISSUE THREAD

**Issue by onbit-syn** [jshttp/on-finished#40]
In the Readme file, there is a grammatical error. There is redundant `for` at the last line of paragraph https://github.com/jshttp/on-finished#http-connect-method.

![image](https://user-images.githubusercontent.com/46771418/115980836-5e014980-a5ad-11eb-8799-bd5a95e29bec.png)

**Comment by lmf-git** [comment]
There are two, I just came here for that too lol
<img width="799" alt="Screenshot 2021-11-19 at 14 19 50" src="https://user-images.githubusercontent.com/67340984/142637689-419f0c54-0c21-4b5d-bc80-ed9564001d52.png">

**Comment by dougwilson** [comment]
Thanks for the report, folks. I can fix it up this weekend, but if either orlf you like, feel free to make a PR with the doc fixes before then and I'll merge your commit instead of mine 👍
