### ISSUE TITLE
async hooks compatibility？

### ISSUE THREAD

**Issue by czewail** [jshttp/on-finished#42]
今早起来服务起不来了，发现 报了read bind of undefined 错误 一看发现更新用了 async hooks

**Comment by dougwilson** [comment]
Hello, and thank you for the report. We can certainly fix the issue. Unfortunately our current tests do not catch the issue. Can you please either open a pull request to with a fix for your issue or provide details like the version of this module, the version of Node.js, and complete code and steps to reproduce the issue? Thank you!

**Comment by czewail** [comment]
`asyncResource.runInAsyncScope` added on Node.js 8.12.0 , if below this version，app will crash

**Comment by dougwilson** [comment]
This has been fixed in version 2.4.1
